/* audio.js — Web Audio API synthesised sound effects.
 *
 * No audio files are loaded; every effect is a small chord/sweep generated by
 * an OscillatorNode + GainNode pair.
 *
 * Browsers refuse to start AudioContext until the user interacts. The game
 * calls `Audio.resume()` from the first keydown to unlock playback.
 */
(function (global) {
  'use strict';

  let ctx = null;

  function getCtx() {
    if (ctx) return ctx;
    try {
      const Ctor = window.AudioContext || window.webkitAudioContext;
      if (!Ctor) return null;
      ctx = new Ctor();
      return ctx;
    } catch (e) {
      return null;
    }
  }

  // Play one short tone with optional pitch slide.
  function tone({ freq, type = 'square', dur = 0.1, vol = 0.18, slide = 0 }) {
    const c = getCtx();
    if (!c) return;
    const osc = c.createOscillator();
    const gain = c.createGain();
    osc.type = type;
    const t = c.currentTime;
    osc.frequency.setValueAtTime(freq, t);
    if (slide) {
      // Linear slide from `freq` to `freq + slide` Hz over the duration.
      osc.frequency.linearRampToValueAtTime(Math.max(40, freq + slide), t + dur);
    }
    gain.gain.setValueAtTime(vol, t);
    gain.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    osc.connect(gain);
    gain.connect(c.destination);
    osc.start(t);
    osc.stop(t + dur + 0.02);
  }

  // Play a short sequence of tones.
  function sequence(notes, opts = {}) {
    notes.forEach((note, i) => {
      setTimeout(() => tone(Object.assign({}, opts, note)), i * (opts.gap || 90));
    });
  }

  global.Audio = {
    // First-keypress hook to unlock the AudioContext on browsers that suspend it.
    resume() {
      const c = getCtx();
      if (c && c.state === 'suspended') c.resume();
    },

    jump() {
      tone({ freq: 360, type: 'square', dur: 0.18, vol: 0.14, slide: 280 });
    },

    collect() {
      // Two-note "ding" — fish/yarn pickup.
      tone({ freq: 660, type: 'square', dur: 0.07, vol: 0.16 });
      setTimeout(() => tone({ freq: 988, type: 'square', dur: 0.10, vol: 0.16 }), 60);
    },

    stomp() {
      tone({ freq: 220, type: 'square', dur: 0.12, vol: 0.20, slide: -160 });
    },

    hurt() {
      tone({ freq: 320, type: 'sawtooth', dur: 0.32, vol: 0.18, slide: -220 });
    },

    win() {
      // Ascending major arpeggio.
      sequence(
        [
          { freq: 523 },
          { freq: 659 },
          { freq: 784 },
          { freq: 1046 },
        ],
        { type: 'square', dur: 0.18, vol: 0.16, gap: 130 }
      );
    },

    death() {
      // Falling minor-ish slide.
      sequence(
        [
          { freq: 440 },
          { freq: 370 },
          { freq: 311 },
          { freq: 220 },
          { freq: 165 },
        ],
        { type: 'sawtooth', dur: 0.18, vol: 0.18, gap: 110 }
      );
    },

    coin() {
      tone({ freq: 988, type: 'square', dur: 0.05, vol: 0.16 });
      setTimeout(() => tone({ freq: 1318, type: 'square', dur: 0.10, vol: 0.16 }), 50);
    },
  };
})(window);
