/* audio.js — Web Audio API synthesised sound effects.
 *
 * No audio files are loaded; every effect is a small chord/sweep generated by
 * an OscillatorNode + GainNode pair.
 *
 * Browsers refuse to start AudioContext until the user interacts. The game
 * calls `Audio.resume()` from the first keydown to unlock playback.
 */
(function (global) {
  'use strict';

  let ctx = null;

  // Master GainNodes — one per audio category. SFX and music each route
  // through their own gain node before reaching the destination, so the
  // toggle handlers can drop the gain to 0 and cut sound *instantly*,
  // even when notes that have already been scheduled (Web Audio's
  // pre-scheduling buffer) would otherwise keep playing for a few seconds.
  let sfxGain = null;
  let musicGain = null;

  function getCtx() {
    if (ctx) return ctx;
    try {
      const Ctor = window.AudioContext || window.webkitAudioContext;
      if (!Ctor) return null;
      ctx = new Ctor();
      return ctx;
    } catch (e) {
      return null;
    }
  }

  // Lazily create the per-category gain nodes once the AudioContext exists.
  function ensureGains() {
    const c = getCtx();
    if (!c) return null;
    if (!sfxGain) {
      sfxGain = c.createGain();
      sfxGain.gain.value = 1;
      sfxGain.connect(c.destination);
    }
    if (!musicGain) {
      musicGain = c.createGain();
      musicGain.gain.value = 1;
      musicGain.connect(c.destination);
    }
    return c;
  }

  // Play one short tone with optional pitch slide. Routes through the SFX
  // master gain so toggling FX off cuts already-scheduled tails instantly.
  function tone({ freq, type = 'square', dur = 0.1, vol = 0.18, slide = 0 }) {
    const c = ensureGains();
    if (!c) return;
    const osc = c.createOscillator();
    const gain = c.createGain();
    osc.type = type;
    const t = c.currentTime;
    osc.frequency.setValueAtTime(freq, t);
    if (slide) {
      // Linear slide from `freq` to `freq + slide` Hz over the duration.
      osc.frequency.linearRampToValueAtTime(Math.max(40, freq + slide), t + dur);
    }
    gain.gain.setValueAtTime(vol, t);
    gain.gain.exponentialRampToValueAtTime(0.0001, t + dur);
    osc.connect(gain);
    gain.connect(sfxGain);
    osc.start(t);
    osc.stop(t + dur + 0.02);
  }

  // Play a short sequence of tones.
  function sequence(notes, opts = {}) {
    notes.forEach((note, i) => {
      setTimeout(() => tone(Object.assign({}, opts, note)), i * (opts.gap || 90));
    });
  }

  // Sound-effects on/off. Gated separately from music so the player can mute
  // one without losing the other. The game UI persists the preference; this
  // module just respects it. setSfxEnabled() is the public hook.
  let sfxOn = true;

  global.Audio = {
    // First-keypress hook to unlock the AudioContext on browsers that suspend it.
    resume() {
      const c = getCtx();
      if (c && c.state === 'suspended') c.resume();
    },

    // Independent SFX mute. Music toggle lives in game.js because the music
    // state machine is more involved (start/stop, tempo, panic mode).
    // Snaps the sfxGain to its target value with NO ramp — any tones that
    // were already scheduled get silenced on the same audio frame — and
    // skips creating new ones via the SFX_KEYS gate further down.
    setSfxEnabled(on) {
      sfxOn = !!on;
      const c = ensureGains();
      if (c && sfxGain) {
        sfxGain.gain.cancelScheduledValues(c.currentTime);
        // Direct assignment is equivalent to setValueAtTime(v, now) AND it
        // updates AudioParam.value as observed by the next read — important
        // when the gate below reads it.
        sfxGain.gain.value = sfxOn ? 1 : 0;
      }
    },
    isSfxEnabled() { return sfxOn; },

    jump() {
      tone({ freq: 360, type: 'square', dur: 0.18, vol: 0.14, slide: 280 });
    },

    collect() {
      // Two-note "ding" — fish/yarn pickup.
      tone({ freq: 660, type: 'square', dur: 0.07, vol: 0.16 });
      setTimeout(() => tone({ freq: 988, type: 'square', dur: 0.10, vol: 0.16 }), 60);
    },

    stomp() {
      tone({ freq: 220, type: 'square', dur: 0.12, vol: 0.20, slide: -160 });
    },

    hurt() {
      tone({ freq: 320, type: 'sawtooth', dur: 0.32, vol: 0.18, slide: -220 });
    },

    win() {
      // Ascending major arpeggio.
      sequence(
        [
          { freq: 523 },
          { freq: 659 },
          { freq: 784 },
          { freq: 1046 },
        ],
        { type: 'square', dur: 0.18, vol: 0.16, gap: 130 }
      );
    },

    death() {
      // Falling minor-ish slide.
      sequence(
        [
          { freq: 440 },
          { freq: 370 },
          { freq: 311 },
          { freq: 220 },
          { freq: 165 },
        ],
        { type: 'sawtooth', dur: 0.18, vol: 0.18, gap: 110 }
      );
    },

    coin() {
      tone({ freq: 988, type: 'square', dur: 0.05, vol: 0.16 });
      setTimeout(() => tone({ freq: 1318, type: 'square', dur: 0.10, vol: 0.16 }), 50);
    },

    // Player head-bumps a power-up box from below.
    boxHit() {
      tone({ freq: 220, type: 'square', dur: 0.06, vol: 0.18 });
      setTimeout(() => tone({ freq: 165, type: 'square', dur: 0.08, vol: 0.16 }), 30);
    },

    // The cat eats a cat-food can and grows.
    powerUp() {
      sequence(
        [
          { freq: 523 },
          { freq: 659 },
          { freq: 784 },
          { freq: 1046 },
          { freq: 1318 },
        ],
        { type: 'square', dur: 0.10, vol: 0.17, gap: 70 }
      );
    },

    // The cat is hit while big — shrinks back down (descending pair).
    powerDown() {
      tone({ freq: 740, type: 'square', dur: 0.10, vol: 0.18 });
      setTimeout(() => tone({ freq: 494, type: 'square', dur: 0.16, vol: 0.18, slide: -120 }), 90);
    },

    // Cat throws a fishbone — short descending square-wave blip.
    shoot() {
      tone({ freq: 880, type: 'square', dur: 0.06, vol: 0.13, slide: -240 });
    },

    // The cat enters down-pounce — fast descending whoosh.
    pound() {
      tone({ freq: 660, type: 'sawtooth', dur: 0.18, vol: 0.16, slide: -460 });
    },

    // Pound impact on the ground — heavy thump.
    poundLand() {
      tone({ freq: 110, type: 'square', dur: 0.10, vol: 0.20, slide: -50 });
    },

    // Background music — chiptune-style 4-bar loop synthesised in Web Audio.
    // Two voices: a square-wave melody arpeggiating an I–V–vi–IV chord
    // progression in C, and a triangle-wave bass on the chord roots.
    // Schedules one full cycle at a time and re-schedules just before the
    // current one ends. Cheap (~48 oscillators per 7-second loop) and gives
    // the level a "real game" pulse with no audio files.
    // Reset the music gain to full and resume scheduling. Snap to 1 with
    // no ramp; the AudioContext will pick it up on the next audio frame.
    musicStart() {
      const c = ensureGains();
      if (c && musicGain) {
        musicGain.gain.cancelScheduledValues(c.currentTime);
        musicGain.gain.value = 1;
      }
      _music.start();
    },
    // Drop the music gain to 0 immediately so any pre-scheduled notes that
    // would otherwise keep ringing for up to a 4-bar loop are silent on the
    // same audio frame, then stop the scheduler so no new notes are queued.
    // No fade — fades are unreliable because reading gain.value mid-ramp
    // returns the most recently-SET value, not the interpolated one, so a
    // ramp from-current-to-0 can produce a brief pop.
    musicStop() {
      const c = ensureGains();
      if (c && musicGain) {
        musicGain.gain.cancelScheduledValues(c.currentTime);
        musicGain.gain.value = 0;
      }
      _music.stop();
    },
    /** Multiplier on the base tempo (1.0 default, 1.4 for the last-30-s panic). */
    musicTempo(mul) { _music.tempoMul = mul; },
  };

  // Gate every SFX entry-point on `sfxOn`. Done as a post-process here so
  // the actual SFX function bodies above stay short and obvious — adding a
  // new SFX is just a new method, no extra gating boilerplate. resume(),
  // setSfxEnabled / isSfxEnabled, and the music* methods are exempt.
  const SFX_KEYS = [
    'jump','collect','stomp','hurt','win','death','coin',
    'boxHit','powerUp','powerDown','shoot','pound','poundLand',
  ];
  for (const k of SFX_KEYS) {
    const orig = global.Audio[k];
    global.Audio[k] = function () {
      if (!sfxOn) return;
      return orig.apply(this, arguments);
    };
  }

  // ---- music engine, internal --------------------------------------------
  const TEMPO_BPM_BASE = 132;
  const NOTE_TO_SEMI = { C: 0, D: 2, E: 4, F: 5, G: 7, A: 9, B: 11 };
  function noteFreq(note) {
    // 'C5', 'F#4' etc → Hz. MIDI: C4 = 60, A4 = 69 = 440 Hz.
    const m = note.match(/^([A-G])(#|b)?(-?\d)$/);
    if (!m) return 440;
    let semi = NOTE_TO_SEMI[m[1]];
    if (m[2] === '#') semi += 1;
    if (m[2] === 'b') semi -= 1;
    const oct = parseInt(m[3], 10);
    const midi = (oct + 1) * 12 + semi;
    return 440 * Math.pow(2, (midi - 69) / 12);
  }

  // I–V–vi–IV in C, four bars at 4/4, eight 8th-notes per bar of melody,
  // four quarter-notes per bar of bass.
  const MELODY = [
    // C: arpeggio C5 E5 G5 E5 (×2)
    ['C5', 0.5], ['E5', 0.5], ['G5', 0.5], ['E5', 0.5],
    ['C5', 0.5], ['E5', 0.5], ['G5', 0.5], ['E5', 0.5],
    // G: G4 B4 D5 B4 (×2)
    ['G4', 0.5], ['B4', 0.5], ['D5', 0.5], ['B4', 0.5],
    ['G4', 0.5], ['B4', 0.5], ['D5', 0.5], ['B4', 0.5],
    // Am: A4 C5 E5 C5 (×2)
    ['A4', 0.5], ['C5', 0.5], ['E5', 0.5], ['C5', 0.5],
    ['A4', 0.5], ['C5', 0.5], ['E5', 0.5], ['C5', 0.5],
    // F: F4 A4 C5 A4 then a small turnaround on the last beat
    ['F4', 0.5], ['A4', 0.5], ['C5', 0.5], ['A4', 0.5],
    ['F4', 0.5], ['A4', 0.5], ['G4', 0.5], ['E4', 0.5],
  ];
  const BASS = [
    ['C3', 1], ['G3', 1], ['C3', 1], ['G3', 1],
    ['G2', 1], ['D3', 1], ['G2', 1], ['D3', 1],
    ['A2', 1], ['E3', 1], ['A2', 1], ['E3', 1],
    ['F2', 1], ['C3', 1], ['F2', 1], ['C3', 1],
  ];

  function playSequence(seq, startTime, beatDur, type, vol) {
    const c = ensureGains();
    if (!c) return startTime;
    let t = startTime;
    for (const [note, beats] of seq) {
      const dur = beats * beatDur;
      const osc = c.createOscillator();
      const gain = c.createGain();
      osc.type = type;
      osc.frequency.setValueAtTime(noteFreq(note), t);
      // Quick attack, soft tail. Stops a hair before the next note to give
      // the square wave a tiny pulse separation rather than a slur.
      gain.gain.setValueAtTime(0.0001, t);
      gain.gain.linearRampToValueAtTime(vol, t + 0.005);
      gain.gain.linearRampToValueAtTime(vol * 0.85, t + dur * 0.6);
      gain.gain.exponentialRampToValueAtTime(0.0001, t + dur * 0.95);
      osc.connect(gain);
      gain.connect(musicGain);
      osc.start(t);
      osc.stop(t + dur + 0.02);
      t += dur;
    }
    return t;
  }

  const _music = {
    playing: false,
    tempoMul: 1.0,
    nextLoopAt: 0,
    timerId: null,

    start() {
      if (this.playing) return;
      const c = getCtx();
      if (!c) return;
      this.playing = true;
      this.nextLoopAt = c.currentTime + 0.1;
      this._scheduleLoop();
    },

    stop() {
      this.playing = false;
      if (this.timerId) { clearTimeout(this.timerId); this.timerId = null; }
      // Outstanding scheduled oscillators will still play out their tails;
      // that's preferable to a sudden cut.
    },

    _scheduleLoop() {
      if (!this.playing) return;
      const c = getCtx();
      if (!c) return;
      const beatDur = 60 / (TEMPO_BPM_BASE * this.tempoMul);
      const start = Math.max(c.currentTime + 0.02, this.nextLoopAt);
      playSequence(MELODY, start, beatDur, 'square', 0.05);
      playSequence(BASS,   start, beatDur, 'triangle', 0.08);
      const loopDur = 16 * beatDur;          // 4 bars × 4 beats
      this.nextLoopAt = start + loopDur;
      // Re-schedule a touch before this loop ends so notes don't gap.
      this.timerId = setTimeout(() => this._scheduleLoop(), (loopDur - 0.15) * 1000);
    },
  };
})(window);
